### ISSUE TITLE
Cannot compile along how-to in wiki

### ISSUE THREAD

**Issue by perahoky** [reyandme/kam_remake#84]
Hello,

i would like to look into your project and compile.
i've followed the steps in https://github.com/reyandme/kam_remake/wiki/ProjectCompilation but the compilation of RXXPacker failed at first try:

compile .\RXXPacker\RXXPacker.lpi
`KM_CommonUtils.pas(87,13) Error: Function is already declared Public/Forward "KMSwapFloat(var Double;var Double);"`

KM_CommonUtils.pas(87,13): 
`  procedure KMSwapFloat(var A,B: Extended); overload;       `

I'm getting several other errors when i try to fix it by trial&error (remove the "duplicate" function).

i've installed Lazarus v2.0.6 2019-10-27 (FPC 3.0.4).

Does it require VCL and native delphi IDE or something similar not free available o.O?

keep up your good work :)

**Comment by reyandme** [comment]
Hi,

Unfortunally Lazarus support is postponed atm, since active development is going on Delphi only. Its still possible to fix Lazarus/FPC compilation issues in the future, if needed.

So to start with Delphi you can try to download free Delphi Community Edition from here:
https://www.embarcadero.com/products/delphi/starter

Feel free to ask any questions, I'll try to help. 
But it will be much easier on discord at KaM Remake official discord channel. 
Join here: https://discord.gg/jTgEsG

good luck

**Comment by reyandme** [comment]
Also 1 guy tried to fix project compilation under Lazarus. We are working on it atm and got some success. So there is a big chance project will be possible to compile under Lazarus / FPC

**Comment by reyandme** [comment]
Ok, we fixed compilation issues for Lazarus. Will update instructions on wiki soon

**Comment by reyandme** [comment]
fixed instructions on wiki:
https://github.com/reyandme/kam_remake/wiki/ProjectCompilation

**Comment by AndreiCherniaev** [comment]
In function LoadUnitsDat I suggest add more userfriendly Assert(FileExists(aPath)). I ma new in KAM building so I forgot add resourses files to directory. May IDE helps me? Now I get message

Exception EAssertionFailed in module KaM_Remake.exe at 002F9127.
Assertion failure (KM_ResUnits.pas, line 555).

I suggest @reyandme  add message "May be you forgot add resourses to build folder? Look https://github.com/reyandme/kam_remake/wiki/ProjectCompilation "



```
function TKMResUnits.LoadUnitsDat(const aPath: UnicodeString): Cardinal;
const
  UNIT_DAT_COUNT = 41;
var
  S: TKMemoryStream;
  I: Integer;
begin
  Assert(FileExists(aPath));

  S := TKMemoryStreamBinary.Create;
  try
    S.LoadFromFile(aPath);

    S.Read(fSerfCarry, SizeOf(fSerfCarry){28*8*70});

    for I := 0 to UNIT_DAT_COUNT - 1 do
    if UNIT_ID_TO_TYPE[I] <> utNone then
      fItems[UNIT_ID_TO_TYPE[I]].LoadFromStream(S)
    else //Skip
      S.Seek(SizeOf(TKMUnitDat) + SizeOf(TKMUnitSprite) + SizeOf(TKMUnitSprite2), soFromCurrent);

    Result := Adler32CRC(S);
  finally
    S.Free;
  end;
end;
```
